In [1]:
import numpy as np

In [17]:
thai_p_matrix = np.matrix('.1, .7, .2; 0.1, 0.4, 0.5; 0.4, 0.3, 0.3')
thai_p_matrix

matrix([[0.1, 0.7, 0.2],
        [0.1, 0.4, 0.5],
        [0.4, 0.3, 0.3]])

In [11]:
np.dot(thai_p_matrix,np.dot(thai_p_matrix, thai_p_matrix))

array([[0.229, 0.405, 0.366],
       [0.211, 0.438, 0.351],
       [0.196, 0.425, 0.379]])

Using @ operator

In [19]:
thai_p_matrix @ thai_p_matrix @ thai_p_matrix

matrix([[0.229, 0.405, 0.366],
        [0.211, 0.438, 0.351],
        [0.196, 0.425, 0.379]])

So, $ P(Mainland\,on\,day\,3) $ is **0.229**